### ISSUE TITLE
2.0.0 Milestone Checklist

### ISSUE THREAD

**Issue by Kodemon** [bentojs/api#21]
Core
  - [x] ~~omit [ [api-core #19](https://github.com/bentojs/api-core/issues/19) ]~~ DISCONTINUED
  - [x] intercom [ [api-core #20](https://github.com/bentojs/api-core/issues/20) ]
  - [x] services *re-evaluate core services, might be a better idea to not have this in core*
  - [x] group *attach group to payload and query strings if interface is enabled*
  - [x] take Route of the global scope, replace with `bento.router((route) => { ... })`
  - [ ] model.access for CRUD, make sure the acting user has the required access to act upon models. [ [#20](https://github.com/bentojs/api/issues/20) ]

Middleware

  - [x] add _auditor to queries and payloads

Documentation
  - [ ] ./api/docs

Database
  - [x] rename api-sequelize to api-mysql to avoid confusion about feature support

Attributes - ensure all related model attributes do not include an `Id` suffix.
- [x] api-auth
- [x] api-core
- [x] api-email
- [x] api-file
- [x] api-log
- [x] api-mysql
- [x] api-queue
- [x] api-role
- [x] api-slack
- [x] api-user
- [x] api-verification

**Comment by Kodemon** [comment]
closed for now
